pimcore:
    custom_views:
        definitions:
            d47c17fb-2cad-c4dd-6301-c28efa40407e:
                name: Products
                treetype: object
                position: left
                rootfolder: /Products
                showroot: true
                sort: 0
                treeContextMenu:
                    object:
                        items:
                            add: true
                            addFolder: true
                            importCsv: true
                            cut: true
                            copy: true
                            paste: true
                            delete: true
                            rename: true
                            reload: true
                            publish: true
                            unpublish: true
                            searchAndMove: true
                            lock: true
                            unlock: true
                            lockAndPropagate: true
                            unlockAndPropagate: true
                            changeChildrenSortBy: true
                classes: '3'
                joins: {  }
                id: d47c17fb-2cad-c4dd-6301-c28efa40407e
                icon: /bundles/pimcoreadmin/img/flat-color-icons/package.svg
